name: Publish
on:
  push:
    branches:
      - 'dev/**'

run-name: Publish $GITHUB_REF_NAME

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: openjdk:17-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build publish -x test --stacktrace
        env:
          MAVEN_PUBLISH_CREDENTIALS: ${{ secrets.MAVEN_PUBLISH_CREDENTIALS }}
